### ISSUE TITLE
directory existence bug

### ISSUE THREAD

**Issue by lteu** [CP-Unibo/sunny-as#1]
When this command is executed for the 2nd time, there would be a directory existence bug
$python src/evaluate_scenarios.py

**Comment by ramadini** [comment]
As clearly written in the README file:

"The file evaluate_scenarios.py can be used for testing the different scenarios 
of ASlib version 1.0.1 (contained in the "data" folder)."

So it is just an helper for evaluating scenarios, nothing more than a sample for doing a little testing. As written in the README, the commands to use should be: train_scenario, test_scenario, split_scenario, pre_process. Actually I don't even remember how does evaluate_scenarios.py work, but I'm pretty sure your patch is wrong (what's its meaning? It looks like just a workaround for not executing the loop, so for doing nothing at all...). I will revert your commit. 
**\* IMPORTANT **\* Please be sure of what you're doing before committing any change, and most important don't push your commit in the master branch, but create a separate branch instead!!!

**Comment by lteu** [comment]
there’s a problem in line 60 of the script,
https://github.com/CP-Unibo/sunny-as/blob/master/src/evaluate_scenarios.py https://github.com/CP-Unibo/sunny-as/blob/master/src/evaluate_scenarios.py
for subdir, dirs, files in os.walk(path + '/cv_' + scenario):

os.walk would examine all the subdirectories of the given path: 'path + '/cv_' + scenario’, 
if you execute for the first time this script it’s fine,
if you do it for the second time, the command os.walk would include a newly created folder ‘kb_train_1_3’(for example) and treat it as folder ’train_1_3’, then do the same execution with  ‘kb_train_1_3’ as it does with ’train_1_3’ which would lead a crash.

Using os.listdir instead of os.walk, or put another check, this problem would be solved.

This is only a suggestion to make the script evaluate_scenarios.py https://github.com/CP-Unibo/sunny-as/blob/master/src/evaluate_scenarios.py more reusable.

Tong

**Comment by ramadini** [comment]
Again, please note that:
- evaluate_scenario.py is just a beta script, don't have to care about it and don't use it as a baseline.
- Your solution is however not a solution, it just avoids to execute the training. Delete the already created folders if you want to fix the script (again: why focusing on this beta script???) for multiple executions. It looks like you don't have idea of how the code works. This is not a problem, but you must pay attention before using/modifying it.
- Suggestions are of course welcome, but pushing code in the master branch is not a suggestion, is adding to the master branch potential rubbish. Please don't do it again, and create a separate branch for your experiments in case.
- Why opening an issue instead of contacting me via mail??? Please avoid to open pointless issues ;)

Roberto.
